### PR TITLE
Handle retried steps.

### PR DESCRIPTION
**Pull request by vmutu**

### CODE REVIEW

**Comment by vmutu** [comment]
I've tested this and can confirm that it handles the Buildkite retried steps correctly now.

**Comment by AustinSchuh** [comment]
Thanks!  We have been hitting this at robotics too.

Can you share the original response and the retried step response from buildkite?  I'd like to confirm there's really nothing we want to track.

**Comment by vmutu** [comment]
Here is the original response before the PR changes (notice the error at the end):
```
Apr  6 09:07:18 ip-10-80-132-4 gep[23226]: 2022/04/06 09:07:18 {"event":"build.running","build":{"id":"0dc66b12-9fc0-42eb-b65b-6ba53608e76b","graphql_id":"QnVpbGQtLS0wZGM2NmIxMi05ZmMwLTQyZWItYjY1Yi02YmE1MzYwOGU3NmI=","url":"https://api.buildkite.com/v2/organizations/myorg/pipelines/mypipeline/builds/10605","web_url":"https://buildkite.com/myorg/mypipeline/builds/10605","number":10605,"state":"running","blocked":false,"blocked_state":"","message":"commit message...","commit":"3cfbe8d4030aeb05466893f9048aa60d2d9c21e8","branch":"I963b020ba1415d392f33329d1b1caed6040592ec","tag":null,"source":"ui","author":null,"creator":{"id":"c37c6f8d-8410-48fa-af3d-416ecd9a88e7","graphql_id":"VXNlci0tLWMzN2M2ZjhkLTg0MTAtNDhmYS1hZjNkLTQxNmVjZDlhODhlNw==","name":"John Doe","email":"john.doe@myco.com","avatar_url":"https://www.gravatar.com/avatar/b575870c7c46cf7b683ef534e9d69901","created_at":"2021-02-04T20:28:49.869Z"},"created_at":"2022-03-23T03:13:24.660Z","scheduled_at":"2022-03-23T03:13:24.619Z","started_at":"2022-04-06T08:11:25.696Z","finished_at":null,"meta_data":{"buildkite:git:commit":"commit details"},"pull_request":null,"ebuilt_from":{"id":"14b34d58-08de-43af-a56b-d63adff03ecc","number":10600,"url":"https://api.buildkite.com/v2/organizations/myorg/pipelines/mypipeline/builds/10600"}},"pipeline":{"id":"78a5785d-ee9b-46dd-81e0-a4850876acb9","graphql_id":"UGlwZWxpbmUtLS03OGE1Nzg1ZC1lZTliLTQ2ZGQtODFlMC1hNDg1MDg3NmFjYjk=","url":"https://api.buildkite.com/v2/organizations/myorg/pipelines/mypipeline","web_url":"https://buildkite.com/myorg/mypipeline","name":"Project all :rocket:","description":"Project CI","slug":"mypipeline","repository":"myrepo","cluster_id":null,"branch_configuration":null,"default_branch":null,"skip_queued_branch_builds":false,"skip_queued_branch_builds_filter":null,"cancel_running_branch_builds":false,"cancel_running_branch_builds_filter":null,"allow_rebuilds":true,"provider":{"id":"private","settings":{}},"builds_url":"https://api.buildkite.com/v2/organizations/myorg/pipelines/mypipeline/builds","badge_url":"https://badge.buildkite.com/cf6f33de889d4b7325e4d7ad8ad9fc9ddd5bbadf5736517561.svg","created_by":{"id":"59a463ba-fea7-450a-8054-f8f885c660b9","graphql_id":"VXNlci0tLTU5YTQ2M2JhLWZlYTctNDUwYS04MDU0LWY4Zjg4NWM2NjBiOQ==","name":"Bob Smith","email":"bob.smith@myco.com","avatar_url":"https://www.gravatar.com/avatar/9a91053f63657ab2dd0c30ed867a646c","created_at":"2021-01-26T01:52:16.718Z"},"created_at":"2021-02-17T01:00:43.224Z","archived_at":null,"env":null,"scheduled_builds_count":0,"running_builds_count":1,"scheduled_jobs_count":0,"running_jobs_count":2,"waiting_jobs_count":0,"visibility":"private","tags":null,"configuration":"pipeline configuration...","artifact_paths":null,"branch_configuration":null,"env":{},"timeout_in_minutes":120,"agent_query_rules":[],"concurrency":null,"parallelism":null}]},"sender":{"id":"c37c6f8d-8410-48fa-af3d-416ecd9a88e7","name":"John Doe"}}
Apr  6 09:07:18 ip-10-80-132-4 gep[23226]: 2022/04/06 09:07:18 build.running: 0dc66b12-9fc0-42eb-b65b-6ba53608e76b 3cfbe8d4030aeb05466893f9048aa60d2d9c21e8 I963b020ba1415d392f33329d1b1caed6040592ec
Apr  6 09:07:18 ip-10-80-132-4 gep[23226]: 2022/04/06 09:07:18 Detected a rebuild of 14b34d58-08de-43af-a56b-d63adff03ecc for build 0dc66b12-9fc0-42eb-b65b-6ba53608e76b
Apr  6 09:07:18 ip-10-80-132-4 gep[23226]: 2022/04/06 09:07:18 Failed to exec: UNIQUE constraint failed: buildkite.id
```

**Review by AustinSchuh — APPROVED** [review]

**Comment by AustinSchuh** [comment]
Nice fix!

The key here is that you need to rebuild the whole build, then rebuild the step.  At that point, we explode.  This fixes that quite well.

**Pull request merged**
